name: reelai
description: "A TikTok clone with AI features"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.8.2
  chewie: ^1.7.4
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  uuid: ^4.2.2
  flutter_cache_manager: ^3.3.1
  giphy_picker: ^2.0.0
  
  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_analytics: ^10.8.5
  firebase_messaging: ^14.7.15
  firebase_app_check: ^0.2.1+13
  google_sign_in: ^6.1.6
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env 